CREATE TABLE [dbo].[RESOURCE_USAGE]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TIME] DATETIME NOT NULL DEFAULT GETUTCDATE() , 
    [CPU_USAGE] INT NOT NULL, 
    [MEMORY_USAGE] INT NOT NULL, 
    [PC_NAME] VARCHAR(50) NULL
)
